# Autogenerated by nbdev

d = { 'settings': { 'branch': 'main',
                'doc_baseurl': '/samplersome',
                'doc_host': 'https://jbwhit.github.io',
                'git_url': 'https://github.com/jbwhit/samplersome',
                'lib_path': 'samplersome'},
  'syms': {'samplersome.core': {'samplersome.core.foo': ('core.html#foo', 'samplersome/core.py')}}}
